/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.FragmentDTO;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BulkCIAttributeLayerScopeDTO
 */
public class BulkCIAttributeLayerScopeDTOTest {
    private final BulkCIAttributeLayerScopeDTO model = new BulkCIAttributeLayerScopeDTO();

    /**
     * Model tests for BulkCIAttributeLayerScopeDTO
     */
    @Test
    public void testBulkCIAttributeLayerScopeDTO() {
        // TODO: test BulkCIAttributeLayerScopeDTO
    }

    /**
     * Test the property 'namePrefix'
     */
    @Test
    public void namePrefixTest() {
        // TODO: test namePrefix
    }

    /**
     * Test the property 'layerID'
     */
    @Test
    public void layerIDTest() {
        // TODO: test layerID
    }

    /**
     * Test the property 'fragments'
     */
    @Test
    public void fragmentsTest() {
        // TODO: test fragments
    }

}
