/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GenericInboundAttribute;
import org.openapitools.client.model.InboundIDMethodByAttribute;
import org.openapitools.client.model.InboundIDMethodByAttributeModifiers;
import org.openapitools.client.model.InboundIDMethodByByUnion;
import org.openapitools.client.model.InboundIDMethodByByUnionInnerInner;
import org.openapitools.client.model.InboundIDMethodByData;
import org.openapitools.client.model.InboundIDMethodByIntersect;
import org.openapitools.client.model.InboundIDMethodByRelatedTempID;
import org.openapitools.client.model.InboundIDMethodByTemporaryCIID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GenericInboundCIIdMethod
 */
public class GenericInboundCIIdMethodTest {
    private final GenericInboundCIIdMethod model = new GenericInboundCIIdMethod();

    /**
     * Model tests for GenericInboundCIIdMethod
     */
    @Test
    public void testGenericInboundCIIdMethod() {
        // TODO: test GenericInboundCIIdMethod
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'caseInsensitive'
     */
    @Test
    public void caseInsensitiveTest() {
        // TODO: test caseInsensitive
    }

    /**
     * Test the property 'attribute'
     */
    @Test
    public void attributeTest() {
        // TODO: test attribute
    }

    /**
     * Test the property 'modifiers'
     */
    @Test
    public void modifiersTest() {
        // TODO: test modifiers
    }

    /**
     * Test the property 'tempID'
     */
    @Test
    public void tempIDTest() {
        // TODO: test tempID
    }

    /**
     * Test the property 'outgoingRelation'
     */
    @Test
    public void outgoingRelationTest() {
        // TODO: test outgoingRelation
    }

    /**
     * Test the property 'predicateID'
     */
    @Test
    public void predicateIDTest() {
        // TODO: test predicateID
    }

    /**
     * Test the property 'inner'
     */
    @Test
    public void innerTest() {
        // TODO: test inner
    }

}
