/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GraphQLQuery
 */
public class GraphQLQueryTest {
    private final GraphQLQuery model = new GraphQLQuery();

    /**
     * Model tests for GraphQLQuery
     */
    @Test
    public void testGraphQLQuery() {
        // TODO: test GraphQLQuery
    }

    /**
     * Test the property 'operationName'
     */
    @Test
    public void operationNameTest() {
        // TODO: test operationName
    }

    /**
     * Test the property 'namedQuery'
     */
    @Test
    public void namedQueryTest() {
        // TODO: test namedQuery
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

}
