/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GridViewColumn;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GridViewConfiguration
 */
public class GridViewConfigurationTest {
    private final GridViewConfiguration model = new GridViewConfiguration();

    /**
     * Model tests for GridViewConfiguration
     */
    @Test
    public void testGridViewConfiguration() {
        // TODO: test GridViewConfiguration
    }

    /**
     * Test the property 'showCIIDColumn'
     */
    @Test
    public void showCIIDColumnTest() {
        // TODO: test showCIIDColumn
    }

    /**
     * Test the property 'writeLayer'
     */
    @Test
    public void writeLayerTest() {
        // TODO: test writeLayer
    }

    /**
     * Test the property 'readLayerset'
     */
    @Test
    public void readLayersetTest() {
        // TODO: test readLayerset
    }

    /**
     * Test the property 'columns'
     */
    @Test
    public void columnsTest() {
        // TODO: test columns
    }

    /**
     * Test the property 'trait'
     */
    @Test
    public void traitTest() {
        // TODO: test trait
    }

}
