/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.IEdmType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IEdmTypeReference
 */
public class IEdmTypeReferenceTest {
    private final IEdmTypeReference model = new IEdmTypeReference();

    /**
     * Model tests for IEdmTypeReference
     */
    @Test
    public void testIEdmTypeReference() {
        // TODO: test IEdmTypeReference
    }

    /**
     * Test the property 'isNullable'
     */
    @Test
    public void isNullableTest() {
        // TODO: test isNullable
    }

    /**
     * Test the property 'definition'
     */
    @Test
    public void definitionTest() {
        // TODO: test definition
    }

}
