/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ILoadConfig
 */
public class ILoadConfigTest {
    private final ILoadConfig model = new ILoadConfig();

    /**
     * Model tests for ILoadConfig
     */
    @Test
    public void testILoadConfig() {
        // TODO: test ILoadConfig
    }

    /**
     * Test the property 'searchLayerIDs'
     */
    @Test
    public void searchLayerIDsTest() {
        // TODO: test searchLayerIDs
    }

    /**
     * Test the property 'writeLayerID'
     */
    @Test
    public void writeLayerIDTest() {
        // TODO: test writeLayerID
    }

}
