/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InboundIDMethodByTemporaryCIID
 */
public class InboundIDMethodByTemporaryCIIDTest {
    private final InboundIDMethodByTemporaryCIID model = new InboundIDMethodByTemporaryCIID();

    /**
     * Model tests for InboundIDMethodByTemporaryCIID
     */
    @Test
    public void testInboundIDMethodByTemporaryCIID() {
        // TODO: test InboundIDMethodByTemporaryCIID
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'tempID'
     */
    @Test
    public void tempIDTest() {
        // TODO: test tempID
    }

}
