/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PredicateDTO
 */
public class PredicateDTOTest {
    private final PredicateDTO model = new PredicateDTO();

    /**
     * Model tests for PredicateDTO
     */
    @Test
    public void testPredicateDTO() {
        // TODO: test PredicateDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'wordingFrom'
     */
    @Test
    public void wordingFromTest() {
        // TODO: test wordingFrom
    }

    /**
     * Test the property 'wordingTo'
     */
    @Test
    public void wordingToTest() {
        // TODO: test wordingTo
    }

}
