/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RelatedCIDTO
 */
public class RelatedCIDTOTest {
    private final RelatedCIDTO model = new RelatedCIDTO();

    /**
     * Model tests for RelatedCIDTO
     */
    @Test
    public void testRelatedCIDTO() {
        // TODO: test RelatedCIDTO
    }

    /**
     * Test the property 'fromCIID'
     */
    @Test
    public void fromCIIDTest() {
        // TODO: test fromCIID
    }

    /**
     * Test the property 'toCIID'
     */
    @Test
    public void toCIIDTest() {
        // TODO: test toCIID
    }

    /**
     * Test the property 'predicateID'
     */
    @Test
    public void predicateIDTest() {
        // TODO: test predicateID
    }

}
