/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AttributeValueType
 */
@JsonAdapter(AttributeValueType.Adapter.class)
public enum AttributeValueType {
  
  TEXT("Text"),
  
  MULTILINE_TEXT("MultilineText"),
  
  INTEGER("Integer"),
  
  JSON("JSON"),
  
  YAML("YAML"),
  
  IMAGE("Image"),
  
  MASK("Mask"),
  
  DOUBLE("Double"),
  
  BOOLEAN("Boolean"),
  
  DATE_TIME_WITH_OFFSET("DateTimeWithOffset");

  private String value;

  AttributeValueType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AttributeValueType fromValue(String value) {
    for (AttributeValueType b : AttributeValueType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AttributeValueType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AttributeValueType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AttributeValueType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AttributeValueType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AttributeValueType.fromValue(value);
  }
}

