/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AttributeState
 */
@JsonAdapter(AttributeState.Adapter.class)
public enum AttributeState {
  
  NEW("New"),
  
  CHANGED("Changed"),
  
  REMOVED("Removed"),
  
  RENEWED("Renewed");

  private String value;

  AttributeState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AttributeState fromValue(String value) {
    for (AttributeState b : AttributeState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AttributeState> {
    @Override
    public void write(final JsonWriter jsonWriter, final AttributeState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AttributeState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AttributeState.fromValue(value);
    }
  }
}

