/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EdmSchemaElementKind
 */
@JsonAdapter(EdmSchemaElementKind.Adapter.class)
public enum EdmSchemaElementKind {
  
  NONE("None"),
  
  TYPEDEFINITION("TypeDefinition"),
  
  TERM("Term"),
  
  ACTION("Action"),
  
  ENTITYCONTAINER("EntityContainer"),
  
  FUNCTION("Function");

  private String value;

  EdmSchemaElementKind(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EdmSchemaElementKind fromValue(String value) {
    for (EdmSchemaElementKind b : EdmSchemaElementKind.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EdmSchemaElementKind> {
    @Override
    public void write(final JsonWriter jsonWriter, final EdmSchemaElementKind enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EdmSchemaElementKind read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EdmSchemaElementKind.fromValue(value);
    }
  }
}

