/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InboundIDMethodByByUnionInnerInner;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * InboundIDMethodByByUnion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-27T12:24:44.894602Z[Etc/UTC]")
public class InboundIDMethodByByUnion {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_INNER = "inner";
  @SerializedName(SERIALIZED_NAME_INNER)
  private List<InboundIDMethodByByUnionInnerInner> inner = null;

  public InboundIDMethodByByUnion() {
  }

  
  public InboundIDMethodByByUnion(
     String type
  ) {
    this();
    this.type = type;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getType() {
    return type;
  }




  public InboundIDMethodByByUnion inner(List<InboundIDMethodByByUnionInnerInner> inner) {
    
    this.inner = inner;
    return this;
  }

  public InboundIDMethodByByUnion addInnerItem(InboundIDMethodByByUnionInnerInner innerItem) {
    if (this.inner == null) {
      this.inner = new ArrayList<>();
    }
    this.inner.add(innerItem);
    return this;
  }

   /**
   * Get inner
   * @return inner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<InboundIDMethodByByUnionInnerInner> getInner() {
    return inner;
  }


  public void setInner(List<InboundIDMethodByByUnionInnerInner> inner) {
    this.inner = inner;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InboundIDMethodByByUnion inboundIDMethodByByUnion = (InboundIDMethodByByUnion) o;
    return Objects.equals(this.type, inboundIDMethodByByUnion.type) &&
        Objects.equals(this.inner, inboundIDMethodByByUnion.inner);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, inner);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InboundIDMethodByByUnion {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    inner: ").append(toIndentedString(inner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("inner");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InboundIDMethodByByUnion
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (InboundIDMethodByByUnion.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in InboundIDMethodByByUnion is not found in the empty JSON string", InboundIDMethodByByUnion.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!InboundIDMethodByByUnion.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InboundIDMethodByByUnion` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      JsonArray jsonArrayinner = jsonObj.getAsJsonArray("inner");
      if (jsonArrayinner != null) {
        // ensure the json data is an array
        if (!jsonObj.get("inner").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `inner` to be an array in the JSON string but got `%s`", jsonObj.get("inner").toString()));
        }

        // validate the optional field `inner` (array)
        for (int i = 0; i < jsonArrayinner.size(); i++) {
          InboundIDMethodByByUnionInnerInner.validateJsonObject(jsonArrayinner.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InboundIDMethodByByUnion.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InboundIDMethodByByUnion' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InboundIDMethodByByUnion> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InboundIDMethodByByUnion.class));

       return (TypeAdapter<T>) new TypeAdapter<InboundIDMethodByByUnion>() {
           @Override
           public void write(JsonWriter out, InboundIDMethodByByUnion value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InboundIDMethodByByUnion read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InboundIDMethodByByUnion given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InboundIDMethodByByUnion
  * @throws IOException if the JSON string is invalid with respect to InboundIDMethodByByUnion
  */
  public static InboundIDMethodByByUnion fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InboundIDMethodByByUnion.class);
  }

 /**
  * Convert an instance of InboundIDMethodByByUnion to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

