/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActiveDirectoryXmlIngestApi
 */
@Ignore
public class ActiveDirectoryXmlIngestApiTest {

    private final ActiveDirectoryXmlIngestApi api = new ActiveDirectoryXmlIngestApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ingestXMLTest() throws ApiException {
        String version = null;
        Long writeLayerID = null;
        List<Long> searchLayerIDs = null;
        List<File> files = null;
        api.ingestXML(version, writeLayerID, searchLayerIDs, files);

        // TODO: test validations
    }
    
}
