/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AnsibleInventoryScanDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnsibleInventoryScanIngestApi
 */
@Ignore
public class AnsibleInventoryScanIngestApiTest {

    private final AnsibleInventoryScanIngestApi api = new AnsibleInventoryScanIngestApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ingestAnsibleInventoryScanTest() throws ApiException {
        Long writeLayerID = null;
        List<Long> searchLayerIDs = null;
        String version = null;
        AnsibleInventoryScanDTO ansibleInventoryScanDTO = null;
        api.ingestAnsibleInventoryScan(writeLayerID, searchLayerIDs, version, ansibleInventoryScanDTO);

        // TODO: test validations
    }
    
}
