/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GraphvizDotApi
 */
@Disabled
public class GraphvizDotApiTest {

    private final GraphvizDotApi api = new GraphvizDotApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void graphvizDotLayerCentricTest() throws ApiException {
        List<String> layerIDs = null;
        OffsetDateTime from = null;
        OffsetDateTime to = null;
        String version = null;
        api.graphvizDotLayerCentric(layerIDs, from, to, version);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void graphvizDotTraitCentricTest() throws ApiException {
        List<String> layerIDs = null;
        String version = null;
        List<String> traitIDs = null;
        String traitIDsRegex = null;
        api.graphvizDotTraitCentric(layerIDs, version, traitIDs, traitIDsRegex);
        // TODO: test validations
    }

}
