/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.io.File;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ImportExportLayerApi
 */
@Disabled
public class ImportExportLayerApiTest {

    private final ImportExportLayerApi api = new ImportExportLayerApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importExportLayerExportLayerTest() throws ApiException {
        String layerID = null;
        String version = null;
        List<UUID> ciids = null;
        api.importExportLayerExportLayer(layerID, version, ciids);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void importExportLayerImportLayerTest() throws ApiException {
        String version = null;
        List<File> files = null;
        String overwriteLayerID = null;
        api.importExportLayerImportLayer(version, files, overwriteLayerID);
        // TODO: test validations
    }

}
