/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OkPluginInsightDiscoveryIngestApi
 */
@Disabled
public class OkPluginInsightDiscoveryIngestApiTest {

    private final OkPluginInsightDiscoveryIngestApi api = new OkPluginInsightDiscoveryIngestApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ingestFileIngestTest() throws ApiException {
        String context = null;
        String version = null;
        String contentType = null;
        String contentDisposition = null;
        Long length = null;
        String name = null;
        String fileName = null;
        api.ingestFileIngest(context, version, contentType, contentDisposition, length, name, fileName);
        // TODO: test validations
    }

}
