/*
 * Landscape omnikeeper REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.threeten.bp.OffsetDateTime;
import org.openapitools.client.model.RelationDTO;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RelationApi
 */
@Ignore
public class RelationApiTest {

    private final RelationApi api = new RelationApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllMergedRelationsTest() throws ApiException {
        List<Long> layerIDs = null;
        String version = null;
        OffsetDateTime atTime = null;
        List<RelationDTO> response = api.getAllMergedRelations(layerIDs, version, atTime);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMergedRelationTest() throws ApiException {
        UUID fromCIID = null;
        UUID toCIID = null;
        String predicateID = null;
        List<Long> layerIDs = null;
        String version = null;
        OffsetDateTime atTime = null;
        RelationDTO response = api.getMergedRelation(fromCIID, toCIID, predicateID, layerIDs, version, atTime);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMergedRelationsFromOrToCITest() throws ApiException {
        UUID ciid = null;
        List<Long> layerIDs = null;
        String version = null;
        OffsetDateTime atTime = null;
        List<RelationDTO> response = api.getMergedRelationsFromOrToCI(ciid, layerIDs, version, atTime);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMergedRelationsOutgoingFromCITest() throws ApiException {
        UUID fromCIID = null;
        List<Long> layerIDs = null;
        String version = null;
        OffsetDateTime atTime = null;
        List<RelationDTO> response = api.getMergedRelationsOutgoingFromCI(fromCIID, layerIDs, version, atTime);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMergedRelationsWithPredicateTest() throws ApiException {
        String predicateID = null;
        List<Long> layerIDs = null;
        String version = null;
        OffsetDateTime atTime = null;
        List<RelationDTO> response = api.getMergedRelationsWithPredicate(predicateID, layerIDs, version, atTime);

        // TODO: test validations
    }
    
}
